apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: observeops-alert-config
  namespace: monitoring
  labels:
    alertmanagerConfig: main
spec:
  route:
    repeatInterval: 30m
    receiver: 'email'
    routes:
    - matchers:
      - name: severity
        value: critical
        matchType: =
      receiver: 'email'
      repeatInterval: 5m
  
  receivers:
  - name: 'email'
    emailConfigs:
    - to: akingbadeomosebi@gmail.com
      from: akingbadeomosebi@gmail.com
      sendResolved: true
      smarthost: smtp.gmail.com:587
      authUsername: akingbadeomosebi@gmail.com
      authIdentity: akingbadeomosebi@gmail.com
      authPassword:
        name: mail-pass
        key: gmail-pass
      headers:
      - key: Subject
        value: '[ObserveOps Alert] {{ .GroupLabels.alertname }}'
